// ═══════════════════════════════════════════════════════════════
// AMMARIA — The Merchant Realms Data Module v1.0
// ═══════════════════════════════════════════════════════════════
// Self-registering supplement module for Glassforge tools.
// Generated from verified canonical JSON data files.
// All data verified against Ammaria regional module (published).
// ═══════════════════════════════════════════════════════════════

(function() {
  var CF = window.CharacterForge;
  if (!CF || !CF.registerModule) { console.error('CharacterForge engine not loaded'); return; }

  CF.registerModule({
    id: 'ammaria',
    name: 'Ammaria — The Merchant Realms',
    description: 'Regional edges, hindrances, equipment, and characters from the Ammaria supplement.',
    alwaysOn: false,
    colour: '#C49A4A',

    // ── EDGES (18) ──
    edges: [
      // Combat Edges (5)
      {name:'Ammarian Halberd Guard',rank:'Novice',type:'Combat',reqs:'Fighting d6+',summary:'When wielding a halberd, polearm, or staff, enemies moving adjacent from outside Reach provoke a free Fighting attack. On Shake or wound, their action ends. One such attack per round.'},
      {name:'Caravan Guard',rank:'Novice',type:'Combat',reqs:'Fighting d6+ or Shooting d6+',summary:'+1 Notice to detect ambushes. +1 Fighting or Shooting (chosen at purchase) during the first round of any combat beginning as an ambush.'},
      {name:'Repeating Crossbow Training',rank:'Novice',type:'Combat',reqs:'Shooting d6+',summary:'Unlocks ROF 2 with repeating crossbows. +2 to Repair or Shooting rolls when clearing jams.'},
      {name:'Repeating Crossbow Mastery',rank:'Seasoned',type:'Combat',reqs:'Repeating Crossbow Training, Shooting d8+',summary:'Ignore Recoil penalty when firing a repeating crossbow at ROF 2.'},
      {name:'War Boar Rider',rank:'Seasoned',type:'Combat',reqs:'Riding d8+',summary:'+2 to Riding rolls involving war boars. Berserk control difficulty reduced by 2. Access to guild breeding stock at 400\u20A1.'},
      // Professional Edges (8)
      {name:'Appraiser',rank:'Novice',type:'Professional',reqs:'Smarts d6+, Notice d6+',summary:'+2 to Notice or Common Knowledge to detect forgeries, identify quality, or estimate fair prices.'},
      {name:'Blackmarket Broker',rank:'Novice',type:'Professional',reqs:'Common Knowledge d6+, Persuasion d6+',summary:'+2 to Common Knowledge to locate buyers or sellers for contraband, stolen property, or restricted items.'},
      {name:'Guild Journeyman',rank:'Novice',type:'Professional',reqs:'Smarts d6+ or Agility d6+, relevant trade skill d6+',summary:'+1 primary trade skill in guild structures. +1 Common Knowledge for guild matters and commercial law. Guild facilities provide lodging and credit.'},
      {name:'Guildmaster',rank:'Seasoned',type:'Professional',reqs:'Guild Journeyman, relevant trade skill d8+',summary:'+2 Persuasion invoking guild authority. Once per session: legal representation, emergency credit (500\u20A1), influential introductions, or guild intelligence.'},
      {name:'Moneylender',rank:'Seasoned',type:'Professional',reqs:'Smarts d8+, Persuasion d6+',summary:'+2 Persuasion involving debt, loans, or financial obligations. Notice roll to spot financial distress in others.'},
      {name:'Photographic Memory',rank:'Novice',type:'Professional',reqs:'Smarts d8+',summary:'+2 Smarts to recall names, faces, documents, maps, and previously encountered information.'},
      {name:'Sailor\'s Edge',rank:'Novice',type:'Professional',reqs:'Boating d6+, Athletics d4+',summary:'Ignore 1 point of unstable platform penalties. +1 Fighting aboard ships. +1 Persuasion with seafarers.'},
      {name:'Smuggler\'s Eye',rank:'Novice',type:'Professional',reqs:'Notice d6+',summary:'+2 Notice to detect hidden compartments, smuggled goods, or concealed weapons.'},
      // Social Edges (2)
      {name:'Patron',rank:'Novice',type:'Social',reqs:'\u2014',summary:'Monthly stipend of 50\u20A1, access to patron\'s social circles, occasional gifts. Must advance patron\'s interests in return.'},
      {name:'Reputation (Commerce)',rank:'Seasoned',type:'Social',reqs:'Persuasion d6+',summary:'+2 Persuasion with merchants, guild members, and anyone who values commercial success.'},
      // Magic Edges (3)
      {name:'Guild Trained',rank:'Novice',type:'Power',reqs:'Arcane Background (any), Smarts d6+',summary:'+2 arcane skill in proper workshop or laboratory. Can jury-rig workspace with Smarts roll.'},
      {name:'Commercial Caster',rank:'Novice',type:'Power',reqs:'Arcane Background (any), Persuasion d6+',summary:'+1 arcane skill for paying clients. +2 Persuasion when negotiating magical service fees.'},
      {name:'Oath-Binder',rank:'Novice',type:'Power',reqs:'Arcane Background (any), Smarts d6+',summary:'+2 arcane skill for powers that bind, compel, detect deception, or enforce agreements.'}
    ],

    // ── HINDRANCES (11 entries, 12 with Minor/Major split) ──
    hindrances: [
      {name:'Collaborator\'s Blood',type:'Minor',summary:'Family suspected of Glasryan service. -1 Persuasion with anyone who\'s heard the stories.'},
      {name:'Country-Born',type:'Minor',summary:'-2 Common Knowledge for guild politics, urban customs, city geography, social etiquettes.'},
      {name:'Dark Reputation',type:'Minor',summary:'-1 Persuasion with anyone who\'s heard the stories. Spreads further the longer you stay in one area.'},
      {name:'Former Slave',type:'Minor/Major',summary:'Minor: Manumitted. -2 Persuasion with respectable Ammarians, legal restrictions. Major: Escaped. As Minor, plus actively hunted.'},
      {name:'Gang Debt',type:'Major',summary:'Owe criminals. -2 vs their Intimidation. Spirit roll to refuse direct requests. Debt may be sold.'},
      {name:'Guild Blacklisted',type:'Major',summary:'Expelled from guild system. Cannot conduct legal trade. Must operate through shadow economy.'},
      {name:'Guild Obligations',type:'Minor',summary:'50\u20A1 annual dues, one week per month guild business, fines for neglect. Called upon at inconvenient times.'},
      {name:'Poverty-Marked',type:'Minor',summary:'-1 Persuasion with social betters. Visible marks of poverty.'},
      {name:'Soft Heart',type:'Minor',summary:'Spirit roll to ignore suffering or prioritise profit over principle.'},
      {name:'Tribute-Touched',type:'Major',summary:'-2 Persuasion vs Glasryans. Spirit roll to resist acting against Imperial interests.'},
      {name:'Unguilded',type:'Minor',summary:'-2 Persuasion in commerce with guild members. Cannot legally practise regulated trades.'}
    ],

    // ── GEAR ──
    gear: {
      ranged: [
        {name:'Repeating Crossbow',range:'15/30/60',dmg:'2d6',ap:3,rof:1,cost:600,wt:12,notes:'Magazine 6, ROF 2 with Training edge, Jam on critical failure'},
        {name:'Hand Crossbow',range:'5/10/20',dmg:'2d4',ap:0,rof:1,cost:150,wt:2,notes:'Concealable (-2 to spot)'},
        {name:'Dock Bow',range:'10/20/40',dmg:'2d6',ap:1,rof:1,cost:60,wt:4,notes:'Marine standard, shortbow'}
      ],
      melee: [
        {name:'Guild Knife',dmg:'Str+d4',cost:25,wt:1,notes:'+1 Stealth to conceal'},
        {name:"Merchant's Cane",dmg:'Str+d4',cost:40,wt:2,notes:'Conceals 18" blade (Str+d4+1)'},
        {name:'War Boar Lance',dmg:'Str+d8',cost:150,wt:6,notes:'Reach 2, AP 2 when charging, mounted only'},
        {name:'Boarding Axe',dmg:'Str+d6',cost:75,wt:3,notes:'+1 to break doors/hatches'},
        {name:"Docker's Hook",dmg:'Str+d4',cost:10,wt:2,notes:'Can grapple at Reach 1'},
        {name:'Weighted Net',dmg:'-',cost:50,wt:4,notes:'Opposed Athletics vs. target Agility to Entangle'},
        {name:"Slaver's Club",dmg:'Str+d4',cost:5,wt:3,notes:'No penalty for nonlethal attacks'},
        {name:'Sap',dmg:'Str+d4',cost:10,wt:0.5,notes:'+2 damage when target unaware, no nonlethal penalty'},
        {name:'Boat Hook',dmg:'Str+d6',cost:20,wt:4,notes:'Reach 1'}
      ],
      armor: [
        {name:'Padded Jacket',armor:1,cost:25,wt:4,notes:'Worn under clothing'},
        {name:'Guild Leathers',armor:2,cost:100,wt:8,notes:'Standard militia issue'},
        {name:"Sailor's Coat",armor:1,cost:75,wt:5,notes:'Water-resistant, reduce swimming penalty by -1'},
        {name:'Ammarian Breastplate',armor:4,cost:900,wt:15,notes:'-1 run penalty (not -2)'},
        {name:'Ammarian Breastplate (Masterwork)',armor:4,cost:1500,wt:12,notes:'No run penalty'},
        {name:'Guild Champion Plate',armor:5,cost:2500,wt:25,notes:'Full plate, guild elite only'},
        {name:'War Boar Barding',armor:3,cost:400,wt:30,notes:'For war boar mounts'},
        {name:'Steel Helm',armor:3,cost:75,wt:4,notes:'Head only'},
        {name:'Open Helm',armor:2,cost:50,wt:3,notes:'Head only, no vision penalty'}
      ],
      shields: [
        {name:'Boarding Shield',parry:1,cost:75,wt:6,notes:'Spiked (Str+d4), +1 vs. entanglement'}
      ],
      general: [
        {name:'Ammarian Lockpicks',cost:100,wt:1,notes:'+1 Thievery'},
        {name:'Guild Scales',cost:25,wt:2,notes:'+1 to appraise weight and purity'},
        {name:'Strongbox',cost:50,wt:8,notes:'Lockable, Toughness 10'},
        {name:'Manacles',cost:15,wt:2,notes:'Strength roll at -2 to break free'},
        {name:'Smoke Bombs (\u00d73)',cost:30,wt:1,notes:'Concealment in Small Burst Template, 3 rounds'}
      ]
    },

    // ── CHARACTERS (20) ──
    characters: [
      // === PRE-GENERATED PLAYER CHARACTERS ===
      {name:'Brother Aldric Stern',refCode:'AM-C001',concept:'Justicar of Valdros',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:6,spirit:10,strength:6,vigor:4},skills:{Athletics:4,'Common Knowledge':4,Faith:8,Fighting:8,Intimidation:6,Notice:6,Persuasion:4,Research:6,Stealth:4},edges:['Arcane Background (Miracles)','Champion','New Powers'],hindrances:['Code of Honor (Major — divine law of Valdros, not guild law)','Stubborn (Minor)','Vengeful (Minor — against those who corrupt justice for profit)'],powers:['Boost Trait','Deflection','Detect/Conceal Arcana','Protection','Smite'],gearText:'Justicar\'s robes over chain shirt (+2), holy symbol of Valdros (focus), Ammarian steel longsword (Str+d8, AP 1), manacles, legal codex, 35₡',abName:'Miracles',abSkill:'Faith',pp:10,quote:'The law is clear. Your interpretation of it is irrelevant.',notes:'Aldric believes absolutely in the law. Not guild law, which bends for money. Not city law, which bends for power. Divine law — the basic principles that bind the world. He\'s watched Ammaria erode those principles for profit. He enforces the law because someone must. He can\'t be bribed. He can\'t be threatened.\n\nAdvancement: Add Combat Reflexes at Seasoned, then Holy Warrior or Block.'},
      {name:'Captain Jorin Saltwind',refCode:'AM-C002',concept:'Moonstar Veteran',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:8,smarts:6,spirit:6,strength:6,vigor:6},skills:{Athletics:6,Boating:8,'Common Knowledge':6,Fighting:6,Notice:6,Persuasion:6,Shooting:6,Stealth:4},edges:['Sailor\'s Edge','Command','Caravan Guard'],hindrances:['Loyal (Minor — to his crew and the Moonstar Consortium)','Cautious (Minor)','Obligation (Minor — Consortium shipping contracts and schedules)'],powers:[],gearText:'Leather armour (+1), cutlass (Str+d6), repeating crossbow (2d6, AP 3, Range 15/30/60), sailor\'s kit, 50₡',quote:'The sea rewards competence. Ammaria rewards calculation. I provide both.',notes:'Twenty years commanding Consortium vessels taught Jorin that maritime profit requires seamanship and shrewd dealing. Commands the Silver Current coastal trader. Conservative in navigation, aggressive in negotiation.\n\nAdvancement: Add Natural Leader at Seasoned, then Combat Reflexes.'},
      {name:'Daven Redstar',refCode:'AM-C003',concept:'Ashmen Enforcer',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:4,spirit:6,strength:10,vigor:8},skills:{Athletics:6,'Common Knowledge':4,Fighting:10,Intimidation:6,Notice:6,Persuasion:4,Shooting:4,Stealth:4},edges:['Brawny','Ammarian Halberd Guard'],hindrances:['Loyal (Minor — to Kira Ironjaw and the Ashmen)','Mean (Minor)','Wanted (Minor — Steel Brotherhood, dishonourable discharge from Aschenfeld)'],powers:[],gearText:'Guild leathers (+2), halberd (Str+d8, AP 1, Reach 1), Ammarian steel shortsword (Str+d6, AP 1), 30₡',quote:'The boss protects her interests. I am the boss\'s interests.',notes:'Former Steel Brotherhood veteran who found new employment after a dishonourable discharge. The Ashmen pay better anyway, and Kira Ironjaw doesn\'t ask questions about what happened in Aschenfeld.\n\nAdvancement: Add Brawny at Novice (with Advance), then Combat Reflexes at Seasoned.'},
      {name:'Elara Vossak',refCode:'AM-C004',concept:'Guild Alchemist',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:10,spirit:6,strength:4,vigor:6},skills:{'Common Knowledge':6,Fighting:4,Healing:6,Notice:6,Persuasion:6,Science:6,Spellcasting:10,Stealth:4},edges:['Arcane Background (Magic)','Alchemist','New Powers'],hindrances:['Curious (Major)','Cautious (Minor)','Obligation (Minor — Apothecaries\' Guild licence terms)'],powers:['Boost/Lower Trait','Environmental Protection','Healing','Light/Darkness','Stun'],gearText:'Alchemist\'s kit, guild seal, journeyman robes, dagger (Str+d4), 3 prepared healing draughts, 45₡',abName:'Magic',abSkill:'Spellcasting',pp:10,quote:'Forty crowns for the batch. The guild seal guarantees potency. What you do with it afterward is your business — and your conscience.',notes:'Journeyman alchemist licensed through the Apothecaries\' Guild. Runs a small shop in Mottgorte. Her official catalogue includes healing draughts and cleaning compounds. Her unofficial catalogue — available to trusted customers — is much wider.\n\nAdvancement: Add Rapid Recharge at Seasoned, then Power Points.'},
      {name:'Kael "Boarheart" Thrace',refCode:'AM-C005',concept:'War Boar Keeper',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:6,spirit:8,strength:8,vigor:4},skills:{Athletics:6,'Common Knowledge':4,Fighting:8,Notice:6,Persuasion:4,Riding:8,Stealth:4,Survival:6},edges:['Beast Bond','Beast Master','Caravan Guard'],hindrances:['Loyal (Minor — to his war boars and their handlers)','Illiterate (Minor)','Poverty-Marked (Minor — farm stock origins, never learned to handle money)'],powers:[],gearText:'Leather armour (+1), spear (Str+d6, Reach 1), short bow (2d6, Range 12/24/48), handler\'s tools, trained war boar companion, 40₡',quote:'People fear cavalry. People flee war boars. There\'s a difference.',notes:'Farm boy who discovered a talent for animal handling with family war boar stock. Now maintains breeding stock and trains mounts for guild cavalry. Protective of his charges.\n\nAdvancement: Add War Boar Rider at Seasoned, then Brawny.'},
      {name:'Lyssa Thorne',refCode:'AM-C006',concept:'Merchant Princess',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:4,smarts:8,spirit:8,strength:4,vigor:6},skills:{Athletics:4,'Common Knowledge':8,Notice:8,Persuasion:10,Research:6,Stealth:4},edges:['Charismatic','Appraiser'],hindrances:['Stubborn (Minor)','Obligation (Minor — Thorne merchant dynasty expectations)','Code of Honor (Major — refuses the slave trade, honours her word even when costly)'],powers:[],gearText:'Fine clothing, 150₡ cash',quote:'Everything negotiable has a price. Everything else? Also negotiable.',notes:'Born into the Thorne merchant dynasty, Lyssa broke her arranged betrothal and now builds her own commercial network. She refuses the slave trade and honours her word even when costly — principled stubbornness hidden behind a polished Ammarian facade.\n\nAdvancement: Add Guild Journeyman at Seasoned, followed by Connections or Rich.'},
      {name:'Magister Conrad Holt',refCode:'AM-C007',concept:'Guild Wizard',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:10,spirit:6,strength:4,vigor:6},skills:{Academics:4,'Common Knowledge':6,Notice:6,Occult:6,Persuasion:6,Research:6,Spellcasting:10,Stealth:4},edges:['Arcane Background (Magic)','Wizard','New Powers'],hindrances:['Curious (Major)','Obligation (Minor — Covenant of Letters duties and contracts)','Quirk (Minor — accepts dangerously unusual contracts to escape boredom)'],powers:['Detect/Conceal Arcana','Dispel','Lock/Unlock','Protection','Speak Language'],gearText:'Covenant robes, seal-ring (focus), spellbook disguised as legal codex, dagger (Str+d4), 120₡',abName:'Magic',abSkill:'Spellcasting',pp:10,quote:'The contract binds both parties equally. Sign here, here, and here. The Covenant seal makes it... enforceable.',notes:'Licensed wizard of the Covenant of Letters. Entered the Covenant because magic fascinated him. Fifteen years later, he spends his days verifying signatures and renewing wards. The work pays well. The work is mind-numbing. Lately, he\'s taken to accepting unusual contracts — authentication jobs in dangerous locations, work for clients the Covenant prefers to avoid.\n\nAdvancement: Add Rapid Recharge at Seasoned, then Soul Drain or Power Points.'},
      {name:'Marus Ironhand',refCode:'AM-C008',concept:'Guild Armourer',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:8,spirit:6,strength:6,vigor:6},skills:{Athletics:4,'Common Knowledge':6,Fighting:6,Intimidation:4,Notice:6,Persuasion:4,Repair:10,Research:6,Stealth:4},edges:['Guild Journeyman','McGyver','Brawny'],edgeNotes:{'Guild Journeyman':'Guild of Iron'},hindrances:['Code of Honor (Minor — refuses to craft weapons for evil purposes)','Loyal (Minor — five-generation Ironhand craftsman family)','Stubborn (Minor)'],powers:[],gearText:'Leather apron (+1), Ammarian steel hammer (Str+d6, AP 1), master tools, 80₡',quote:'Quality speaks. Ammarian quality sings. My work bellows.',notes:'Master armourer from a five-generation craftsman family. Creates weapons and armour that nobles commission and warriors covet. Perfectionist who won\'t craft for evil purposes.\n\nAdvancement: Add Guildmaster at Seasoned, then Mr. Fix It.'},
      {name:'Renna Ashveil',refCode:'AM-C009',concept:'Debt-Slave Gladiator',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:10,smarts:4,spirit:6,strength:8,vigor:4},skills:{Athletics:10,'Common Knowledge':4,Fighting:10,Intimidation:6,Notice:4,Persuasion:4,Stealth:4,Survival:6},edges:['Quick','Combat Reflexes','First Strike'],hindrances:['Obligation (Major — term slavery contract, fights for her master\'s profit)','Poverty (Minor)','Vengeful (Major — against the slavers who hold her contract)'],powers:[],gearText:'Gladiatorial leathers (+1), gladius (Str+d6), net, Ammarian steel dagger (Str+d4, AP 1), 5₡ hidden savings',quote:'Five years contracted. Four hundred seventeen days remain.',notes:'Sold herself into term slavery to discharge family debts. Assigned gladiatorial training for master\'s profit. Shockingly skilled fighter who counts days toward freedom obsessively. Saves every copper toward early contract purchase.\n\nAdvancement: Add Block at Seasoned, then Caravan Guard after earning freedom.'},
      {name:'"Shadows"',refCode:'AM-C010',concept:'Night\'s Whisper Operative',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:10,smarts:6,spirit:6,strength:4,vigor:6},skills:{Athletics:8,'Common Knowledge':4,Fighting:4,Notice:6,Persuasion:4,Stealth:10,Thievery:10},edges:['Thief','Acrobat','Streetwise'],hindrances:['Wanted (Minor — Ammarian Watch, suspected burglaries)','Loyal (Minor — Night\'s Whisper guild members)','Cautious (Minor)','Greedy (Minor)'],powers:[],gearText:'Dark clothing, Ammarian lockpicks (+1 Thievery), guild knife (Str+d4), grappling hook with silk rope, smoke bombs, 60₡',quote:'The guild doesn\'t steal. We relocate assets to more appreciative owners.',notes:'Professional thief affiliated with Arr\'ath\'s premier thieves\' guild. Specialises in burglary and information theft. Strict professional standards: no unnecessary violence, no jobs attracting excessive attention, absolute loyalty to guild members.\n\nAdvancement: Add Fleet-Footed at Seasoned, then Improved Thief.'},
      {name:'Sister Anneke Dreher',refCode:'AM-C011',concept:'Hearthwarden of Mira',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:6,smarts:6,spirit:10,strength:4,vigor:6},skills:{Athletics:4,'Common Knowledge':6,Faith:10,Fighting:4,Healing:6,Notice:6,Persuasion:8,Stealth:4},edges:['Arcane Background (Miracles)','Healer','New Powers'],hindrances:['Heroic (Major)','Soft Heart (Minor)','Poverty (Minor)'],powers:['Healing','Protection','Relief','Sanctuary','Speak Language'],gearText:'Simple robes, hearthkeeper\'s symbol (focus), healer\'s kit, staff (Str+d4, Parry +1, Reach 1), 8₡',abName:'Miracles',abSkill:'Faith',pp:10,quote:'The goddess asks only that we care for each other. Everything else — the politics, the tributes, the guild squabbles — is noise.',notes:'Anneke serves Mira the Hearthkeeper, conducting marriages, namedays, and funerals throughout Mottgorte\'s working-class districts. She knows every family, every feud, every tragedy. The gangs respect her. The Watch tolerates her. The guild temples dismiss her as a peasant comforter. None of them understand what she actually does.\n\nAdvancement: Add Rapid Recharge at Seasoned, then Holy Warrior or Champion.'},
      {name:'Viktor "Silvertongue" Crane',refCode:'AM-C012',concept:'Consortium Factor',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'Pre-gen',product:'Ammaria',attrs:{agility:4,smarts:10,spirit:8,strength:4,vigor:6},skills:{Athletics:4,'Common Knowledge':8,Intimidation:4,Notice:8,Persuasion:10,Research:8,Stealth:4},edges:['Appraiser','Charismatic','Connections'],edgeNotes:{'Connections':'Moonstar Consortium, Council of Guilds contacts'},hindrances:['Arrogant (Minor)','Obligation (Minor — Moonstar Consortium intelligence reports)','Greedy (Minor)'],powers:[],gearText:'Fine clothing, guild credentials, letters of credit, 200₡',quote:'Information is currency. I traffic in both.',notes:'Moonstar Consortium factor who gathers commercial intelligence. Charismatic manipulator who treats complex deals as intellectual puzzles. Secretly reports to Consortium leadership on Council activities.\n\nAdvancement: Add Guild Journeyman at Seasoned, then Investigator.'},

      // === NAMED NPCs (WILD CARDS) ===
      {name:'Aeldric Venca',refCode:'AM-C013',concept:'Senior Factor / Guildmaster',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Veteran',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:10,spirit:8,strength:4,vigor:6},skills:{'Common Knowledge':12,Intimidation:8,Notice:10,Persuasion:10,Research:8},edges:['Guildmaster','Appraiser','Rich','Connections','Strong Willed'],edgeNotes:{'Connections':'Serien Mercantile Council, most senior guild families'},hindrances:[],powers:[],gearText:'Expensive clothing, guild credentials, rings worth more than most houses, private guards (4)',quote:'Guildmaster Venca will see you now. Mind your manners.',notes:'Appendix D: Allies & Contacts.\n\nSenior factor on the Serien Mercantile Council. Guided his trading house to remarkable success over three decades. His rivals have suffered an equally remarkable string of misfortunes: bankruptcies, scandals, convenient accidents, one memorable warehouse fire.\n\nUrbane, patient, speaks softly because he doesn\'t need to raise his voice. Never threatens — simply explains how things are.\n\nThe Truth: Everyone knows what Venca is. Nobody can prove it. The last merchant who tried to expose him vanished en route to the Council Chamber.\n\nHook: Venca has noticed the party. He\'s impressed by their capabilities. The meeting invitation is polite. Declining would be unwise.'},
      {name:'Aldric Brenner',refCode:'AM-C014',concept:'Keeper Agent',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Seasoned',category:'NPC',product:'Ammaria Weekly Pack W01',attrs:{agility:8,smarts:8,spirit:10,strength:6,vigor:6},skills:{Athletics:6,'Common Knowledge':6,Fighting:6,Notice:8,Persuasion:6,Shooting:6,Stealth:8},edges:['Alertness','Strong Willed','Connections'],edgeNotes:{'Connections':'Keeper network, reports to Father Corvin'},hindrances:['Enemy (Major — identified by a Justicar agent)','Secret (Major — Keeper of the Sacred Flame operative)','Vow (Minor — honour the family he lost)'],powers:[],gearText:'Guild credentials, concealed short sword (Str+d6), coded message book, 100₡',quote:'I\'m just a factor. I count inventory. I track shipments. That\'s all.',notes:'Week 01: The Counting Quarter / NPC Pack: Guild Factors.\n\nNo relation to the Grandmaster — a fact he\'s tired of explaining. Forty-three, military bearing gone slightly to seed. Presents as the most boring factor in Mottgorte — soft-spoken, meticulous, forgettable. The perfect middle manager.\n\nIt\'s a mask. Behind the facade, Aldric is a Keeper of the Sacred Flame — resistance operative, information courier, occasional saboteur.\n\nWhat He Wants: To continue the fight. To honour the family he lost.\nHis Secret: He\'s been identified. A Justicar agent has started asking questions. He has weeks before they come for him.\n\nSpecial — Grey Man: +2 to Stealth in urban environments and crowds.\n\nConnections: Reports to Father Corvin (Week 05). Watches Elsbet Kohl\'s investigation with interest. Suspects Viktor Aldenberg has connections worth exploiting.'},
      {name:'Brother Marcus',refCode:'AM-C015',concept:'Keeper Operative',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Seasoned',category:'NPC',product:'Ammaria Weekly Pack W05',attrs:{agility:8,smarts:6,spirit:10,strength:8,vigor:8},skills:{Athletics:8,Fighting:10,Intimidation:8,Notice:6,Shooting:8,Stealth:8,Survival:6},edges:['Combat Reflexes','Brave','First Strike','Fervor'],hindrances:['Vow (Major — destroy Glasryan influence)','Stubborn (Minor)','Wanted (Minor — suspicion of three Glasryan deaths)'],powers:[],gearText:'Sword (Str+d8), crossbow (2d6), leather armour (+1), holy symbol (displayed proudly)',quote:'I survived because it meant something. I\'m still figuring out what.',notes:'Week 05: Keepers and Thieves.\n\nThirty-five, former soldier, former drunk, found religion after a Keeper healer saved his life. Decided his survival meant something. Has been acting on that conviction ever since. The fire in him won\'t go out. That makes him inspiring — and terrifying.\n\nWhat He Wants: To destroy Glasryans. To matter. To prove his survival wasn\'t random.\nHis Secret: He\'s killed Glasryans. Three of them, over seven years, made to look like accidents. He\'s never told anyone.\n\nSpecial — Fervor: +1 Spirit when fighting for faith.\n\nConnections: Reports to Father Corvin. Potential extremist — the Keepers debate whether he\'s their best weapon or their biggest liability.'},
      {name:'Brynn Goldleaf',refCode:'AM-C016',concept:'Merchant Family Junior',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:10,spirit:8,strength:4,vigor:6},skills:{'Common Knowledge':10,Gambling:6,Notice:8,Persuasion:10,Research:6},edges:['Appraiser','Attractive','Rich','Connections'],edgeNotes:{'Connections':'Goldleaf merchant family, black market contacts'},hindrances:[],powers:[],gearText:'Fine clothing, guild credentials, letters of credit (family-backed), 100-200₡',quote:'My family\'s traded spices for six generations. I know things.',notes:'Appendix D: Allies & Contacts.\n\nJunior member of a mid-tier merchant family. Handles the "difficult" transactions her elders prefer not to acknowledge — sales to questionable buyers, purchases from dubious sources, negotiations where plausible deniability matters.\n\nCharming, calculating, genuinely enjoys the game of commerce. More ethical than she pretends — won\'t deal in slaves.\n\nServices: Trade negotiation (+2 to Persuasion, 10% fee), merchant family introduction (50₡), cargo valuation (free), market intelligence (20-50₡)\n\nHook: Brynn\'s discovered her family is involved in something beyond normal corruption — perhaps Glasryan collaboration, perhaps tribute skimming.'},
      {name:'Captain Arckhim Stormwright',refCode:'AM-C017',concept:'Moonstar Captain',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:8,smarts:8,spirit:8,strength:8,vigor:8},skills:{Athletics:8,Boating:10,Fighting:8,Intimidation:6,Notice:8,Shooting:8},edges:['Sailor\'s Edge','Command','Steady Hands','Strong Willed'],hindrances:[],powers:[],gearText:'Reinforced leathers (+2), Ammarian steel cutlass (Str+d6+1, AP 1), pistol crossbow (2d4, 5/10/20), captain\'s coat, 200-400₡',quote:'The Consortium flies our flag, but my ship answers to me.',notes:'Appendix D: Allies & Contacts.\n\nIndependent-minded Moonstar captain whose vessel, the Gilded Serpent, technically serves Consortium interests but frequently takes private contracts that guild headquarters might not approve. Walks a careful line between profitable independence and outright insubordination.\n\nBold, charismatic, fiercely protective of his crew. Takes risks that sometimes pay off spectacularly.\n\nServices: Coastal passage (standard rates minus 20%), "no questions" cargo transport (triple rates), naval escort (negotiable), emergency extraction (500₡+)\n\nHook: Arckhim\'s discovered something during a routine voyage — wreckage, perhaps, or a signal from somewhere it shouldn\'t be.'},
      {name:'Dorgan Ironhide',refCode:'AM-C018',concept:'War Boar Handler',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:8,spirit:10,strength:8,vigor:8},skills:{Athletics:6,Fighting:8,Intimidation:8,Notice:8,Riding:10,Survival:8},edges:['Beast Bond','Beast Master','War Boar Rider'],hindrances:[],powers:[],gearText:'Guild leathers (+2), war boar lance (Str+d8, Reach 2, AP 2 when charging), training gear, personal war boar ("Tusker")',quote:'I train war boars. I train riders. I don\'t train fools.',notes:'Appendix D: Allies & Contacts.\n\nMaster boar-handler maintaining breeding stock and training cavalry for the Guild of Iron. Knows more about war boars than anyone alive — their temperaments, weaknesses, and capabilities. Expensive, temperamental, and absolutely worth it.\n\nGruff, impatient with stupidity, surprisingly gentle with animals. Respects courage; despises cruelty.\n\nServices: War boar training (100₡, 4 weeks), advanced training (200₡, 8 weeks), boar purchase (400-600₡/day)\n\nHook: Someone\'s been poisoning war boars in the guild stables. Dorgan suspects sabotage — maybe agitators, maybe rival guild.'},
      {name:'Elsbet Kohl',refCode:'AM-C019',concept:'The Honest Factor',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria Weekly Pack W01',attrs:{agility:6,smarts:8,spirit:8,strength:4,vigor:6},skills:{Academics:6,'Common Knowledge':8,Notice:8,Persuasion:6,Research:10,Stealth:4},edges:['Investigator','Connections'],edgeNotes:{'Connections':'Textile Guild, former friend of Marta Vries'},hindrances:['Loyal (Minor — to her missing brother Mikael)','Code of Honor (Minor — honest dealing, refuses corruption)'],powers:[],gearText:'Guild credentials, ledger books, modest clothes, 50₡, hidden documents',quote:'I don\'t sell trust. I earn it. That\'s why my clients pay premium rates.',notes:'Week 01: The Counting Quarter / NPC Pack: Guild Factors.\n\nThirty-four, plain clothes that cost more than they appear to, ink-stained fingers. Factor for the Textile Guild — honest work for honest pay. Her brother Mikael disappeared three months ago. The official story: he absconded with guild funds. Elsbet doesn\'t believe it.\n\nShe\'s been investigating quietly. The trail leads somewhere she doesn\'t want to go.\n\nWhat She Wants: To find her brother. To expose the truth.\nHer Secret: She\'s started keeping her own records — documenting irregularities, noting patterns. If something happens to her, the documents go to people who\'ll use them.\n\nSpecial — Pattern Recognition: +2 to Notice rolls involving documents, records, or commercial irregularities.\n\nConnections: Sister of Mikael Kohl. Client in The Counterfeit Seal. Former friend of Marta Vries.'},
      {name:'Guildmaster Aldric Varen',refCode:'AM-C020',concept:'Corrupt Guildmaster',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Veteran',category:'NPC',product:'Ammaria Weekly Pack W01',attrs:{agility:4,smarts:10,spirit:8,strength:4,vigor:6},skills:{'Common Knowledge':10,Intimidation:8,Notice:8,Persuasion:10,Research:6},edges:['Guildmaster','Rich','Connections','Strong Willed'],edgeNotes:{'Connections':'Viktor Aldenberg, Brotherhood enforcers'},hindrances:['Greedy (Major)','Secret (Major — skimming 12,000 crowns of Tribute over five years)','Elderly (Minor)'],powers:[],gearText:'Guild chain of office, expensive clothing, private guards (4), letters of credit, 500₡',quote:'The Tribute shortfall is a clerical matter. It will be resolved. It always is.',notes:'Week 01: The Counting Quarter — Background Antagonist.\n\nSixty-three, silver hair swept back, guild chain worn like armour. Skimmed approximately 12,000 crowns of Tribute over five years. Viktor Aldenberg manages the laundering. The Brotherhood provides enforcement.\n\nVaren is a political animal — dangerous not because he fights, but because he controls the system.\n\nHis Secret: The Glasryans are starting to notice the shortfall. The audit next month terrifies him.\n\nConnections: Viktor Aldenberg manages his money. Brotherhood provides enforcement. Mikael Kohl discovered the theft.'},
      {name:'Ilsa Brennholm',refCode:'AM-C021',concept:'Factor, Timber Trade Association',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria Weekly Pack W04',attrs:{agility:6,smarts:10,spirit:6,strength:4,vigor:6},skills:{Academics:6,'Common Knowledge':8,Notice:6,Persuasion:10,Research:8,Stealth:4,Taunt:6},edges:['Connections','Streetwise'],edgeNotes:{'Connections':'Timber Trade Association, blackmail leverage on senior guild members'},hindrances:['Greedy (Minor)','Obligation (Major — 8,000-crown blackwood shipment, last chance)','Ruthless (Minor)'],powers:[],gearText:'Fine clothes (road-worn), guild credentials, 200₡ in letters of credit, concealed dagger (Str+d4), coded ledger',quote:'Everyone has a price. The trick is finding out what currency they accept.',notes:'Week 04: The Amber Road — The Cargo Owner.\n\nThirty-one, polished facade cracking under pressure. This 8,000-crown blackwood shipment is her last chance. If it arrives intact, she\'s saved. If it doesn\'t, she loses everything.\n\nHer Secret: Contingency plans include documents that could embarrass several senior guild members. Blackmail isn\'t honourable, but neither is starving.\n\nDesperate Measures: When shipment or life is directly threatened, +2 to Persuasion and Intimidation.'},
      {name:'Jens Gruber',refCode:'AM-C022',concept:'Wagonmaster',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria Weekly Pack W04',attrs:{agility:6,smarts:8,spirit:8,strength:6,vigor:8},skills:{Athletics:4,'Common Knowledge':8,Driving:10,Fighting:6,Intimidation:6,Notice:8,Persuasion:6,Repair:8,Shooting:6,Survival:8},edges:['Steady Hands','Woodsman'],hindrances:['Elderly (Minor)','Enemy (Major — Scarface Tomas wants revenge for his uncle)','Stubborn (Minor)'],powers:[],gearText:'Crossbow (2d6, 15/30/60), hand axe (Str+d6), heavy coat, 40₡',quote:'I\'ve buried more friends than I can count. Most of them trusted someone they shouldn\'t have.',notes:'Week 04: The Amber Road — Wagonmaster.\n\nFifty-three, short sentences and long silences. Forty years on the Amber Road. Survived seventeen ambushes, three guild wars, and one forest troll. Eight years ago he testified against Brotherhood enforcer Aleksar Tomas — watched the man hang. "Scarface" Tomas wants revenge.\n\nHis Secret: His testimony wasn\'t entirely heroic. The Brotherhood threatened his wife. She died three years later. He\'s never stopped wondering.\n\nOld Hand: +2 to Common Knowledge about Guildwood trade routes and caravan operations.'},
      {name:'Lenn "Whisper"',refCode:'AM-C023',concept:'Locksmith Between Two Masters',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria Weekly Pack W05',attrs:{agility:10,smarts:8,spirit:6,strength:6,vigor:6},skills:{Athletics:8,Fighting:6,Notice:8,Persuasion:6,Stealth:10,Thievery:12},edges:['Thief','Luck','Lockpicking Specialist'],hindrances:['Loyal (Minor — to both guild and Keepers)','Obligation (Minor — Night\'s Whisper guild dues and jobs)','Obligation (Minor — Keeper network, repaying his mother\'s rescue)'],powers:[],gearText:'Lockpicks (masterwork), dark clothes, rope, grappling hook, 50₡',quote:'Locks talk to me. It\'s people I can\'t figure out.',notes:'Week 05: Keepers and Thieves.\n\nTwenty-eight, mutters to mechanisms while he works, best locksmith in Mottgorte. His guild trained him and pays his rent. The Keepers saved his mother. He owes both. He can\'t betray either.\n\nWhat He Wants: A way out that doesn\'t destroy everyone he cares about.\nHis Secret: He\'s been skimming from Night\'s Whisper for years. Small amounts, funnelled to the Keepers. If his guild finds out, he\'s dead.\n\nSpecial — Lockpicking Specialist: +2 Thievery for locks specifically.\n\nConnections: Night\'s Whisper locksmith. Keeper ally. Key NPC for Week 05 heist. Caught between two obligations with no clean resolution.'},
      {name:'Lyssa Voss',refCode:'AM-C024',concept:'Escaped Slave / Underground Railroad',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:8,smarts:8,spirit:10,strength:6,vigor:8},skills:{Athletics:6,Fighting:8,Notice:8,Persuasion:8,Stealth:8,Survival:8},edges:['Brave','Strong Willed','Connections'],edgeNotes:{'Connections':'Underground railroad network, rebel contacts'},hindrances:['Wanted (Major — escaped slave, bounty active)','Enemy (Major — slave traders hunting her network)'],powers:[],gearText:'Dark clothing, guild knife (Str+d4), forged freedom papers, safe house locations (memorised), 20-50₡',quote:'I survived the pens. I survived escape. You think your problems scare me?',notes:'Appendix D: Allies & Contacts.\n\nFormer slave who escaped a tribute convoy three years ago and has spent every day since helping others do the same. Operates a clandestine network smuggling escaped slaves out of Ammaria. Rebellious to the Dragon Throne but independent — rebellious circles help when convenient, but Lyssa\'s mission comes first.\n\nIntense, driven, surprisingly compassionate. Judges people by actions, not words. Slow to trust but absolutely loyal once won.\n\nServices: Escaped slave transport (free), rebel contact introduction (trust must be earned), safe house access (emergencies only), forgery contacts (50₡)\n\nHook: One of Lyssa\'s safe houses has been compromised. Someone talked — or someone infiltrated.'},
      {name:'Marta Voss',refCode:'AM-C025',concept:'Cook (Formerly Sergeant, Ironhall Militia)',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Seasoned',category:'NPC',product:'Ammaria Weekly Pack W04',attrs:{agility:8,smarts:6,spirit:8,strength:6,vigor:8},skills:{Athletics:6,Battle:6,Fighting:10,Intimidation:8,Notice:8,Shooting:8,Stealth:6,Survival:8},edges:['Combat Reflexes','First Strike','Command','Soldier'],hindrances:['Secret (Major — former militia sergeant, killed her commander)','Wanted (Major — 500 crown bounty from a Grandmaster\'s family)','Death Wish (Minor)'],powers:[],gearText:'Hidden short sword (Str+d6), two throwing knives (Str+d4, 3/6/12), light leather (+1) under cook\'s clothing, forged papers',quote:'Anyone can kill. The hard part is living with it after.',notes:'Week 04: The Amber Road — Hidden Muscle.\n\nForty-five, moves like someone trying not to be noticed. Twenty years in the Ironhall Guild Militia, sergeant by merit. Three years ago her commander ordered her to clear a village. The intelligence was wrong. She refused. The commander drew his sword. What happened next took four seconds.\n\nHer Secret: The commander was nephew to a guild Grandmaster. Bounty — alive, for private justice — is 500 crowns.\n\nHidden Competence: Conceals her abilities until lives are at stake. Once revealed, cannot return to anonymity.\n\nConnections: Future appearances in Week 17 (The Burned Ledger).'},
      {name:'Marta Vries',refCode:'AM-C026',concept:'The Desperate Factor',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria Weekly Pack W01',attrs:{agility:6,smarts:8,spirit:4,strength:4,vigor:6},skills:{'Common Knowledge':6,Notice:6,Persuasion:8,Research:6,Stealth:6,Thievery:4},edges:['Attractive'],hindrances:['Obligation (Major — dead husband\'s debts to the Brotherhood)','Poverty (Minor)','Yellow (Major)'],powers:[],gearText:'Guild credentials, modest clothes, concealed knife (Str+d4), 12₡',quote:'You don\'t understand. I\'m out of options. I\'m out of time.',notes:'Week 01: The Counting Quarter / NPC Pack: Guild Factors.\n\nTwenty-nine, drowning. Married young to a merchant who seemed prosperous — until the gambling debts caught up. He hanged himself in their bedroom. Left her everything, including debts to the Brotherhood.\n\nThe Grain Guild doesn\'t know. If they found out, she\'d lose everything.\n\nWhat She Wants: To survive. To clear her husband\'s debts. To stop feeling afraid.\nHer Secret: She sold out Mikael Kohl. Not for money — to reduce her own debt. She hates herself for it. She\'d do it again.\n\nSpecial — Breaking Point: When Marta\'s situation becomes untenable, she must make a Spirit roll or take whatever escape presents itself.\n\nConnections: Reluctant witness in The Counterfeit Seal. Former friend of Elsbet Kohl. Owned by the Brotherhood.'},
      {name:'Mikael Kohl',refCode:'AM-C027',concept:'The Missing Factor',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria Weekly Pack W01',attrs:{agility:4,smarts:10,spirit:8,strength:4,vigor:6},skills:{Academics:8,'Common Knowledge':10,Notice:8,Persuasion:4,Research:10},edges:['Eidetic Memory','Scholar'],hindrances:['Cautious (Minor)','Loyal (Minor — to his sister Elsbet)'],powers:[],gearText:'Nothing (prisoner)',notes:'Week 01: The Counting Quarter.\n\nElsbet\'s brother. Discovered Tribute fraud. Now he\'s a prisoner. Thirty-one, thin, ink-stained fingers even in captivity. He memorised the evidence — dates, amounts, names — because he knew they\'d search for documents.\n\nWhat He Wants: To survive. To see his sister again. To see justice done.\nHis Secret: He hasn\'t broken yet, but he\'s close. Three more days and he\'ll give them what they want.\n\nConnections: Brother of Elsbet Kohl. Discovered Varen\'s Tribute theft. Held by Brotherhood.'},
      {name:'"Scarface" Tomas',refCode:'AM-C028',concept:'Brotherhood Crew Boss',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria Weekly Pack W04',attrs:{agility:8,smarts:6,spirit:6,strength:8,vigor:8},skills:{Athletics:6,Fighting:8,Notice:6,Shooting:8,Stealth:8},edges:['First Strike','Quick'],hindrances:['Overconfident (Major)','Greedy (Minor)'],powers:[],gearText:'Short sword (Str+d6), crossbow (2d6, AP 2, Range 15/30/60), leather (+1), buckler (+1 Parry)',quote:'The Halberd Guard doesn\'t patrol the Underguild after dark. Everyone knows this.',notes:'Encounter: The Canal Bridge Ambush / Weekly Pack W04.\n\nFormer dockworker, three years running ambushes for the Brotherhood of the Fallen Star. Overconfident — which is a problem when the targets aren\'t what they seem.\n\nTomas earned his scar in a knife fight at seventeen. He\'s been trading on the reputation ever since. Good at what he does — organising crews, planning ambushes, splitting loot fairly enough to keep people loyal. Not good enough to spot when he\'s being played.\n\nTactics: Leads from ambush, opens with crossbow fire, then closes with sword. Relies on numerical advantage and surprise. When outmatched, his Overconfident hindrance prevents smart retreats.\n\nConnections: Brotherhood enforcer. Featured in Week 04 caravan ambush. Returns in Weeks 12 and 22.'},
      {name:'Sergeant Mira Valdos',refCode:'AM-C029',concept:'War Boar Rider',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Seasoned',category:'NPC',product:'Ammaria',attrs:{agility:8,smarts:6,spirit:8,strength:8,vigor:8},skills:{Athletics:6,Fighting:10,Notice:6,Riding:10,Shooting:6,Stealth:4},edges:['Cavalry Charge','Steady Hands','Combat Reflexes'],hindrances:['Loyal (Minor — to her riders and the Halberd Guard)','Overconfident (Major)'],powers:[],gearText:'Lance (Str+d8, AP 2 when charging, Reach 2), Ammarian Breastplate (+2), shield (+1 Parry)',quote:'Fifteen years in the saddle. I\'ve buried friends, broken bones, and charged things that should have killed me. I love this job.',notes:'Encounter: The Canal Bridge Ambush / Appendix D.\n\nWar Boar rider, fifteen years\' service, knows this is a trap and relishes it. Rides Tusker, a veteran war boar with more combat experience than most soldiers.\n\nValdos is the Halberd Guard\'s best mounted combatant — aggressive, disciplined, and completely fearless on boarback. She leads from the front because that\'s where the fighting is.\n\nTactics: Charges with lance for devastating first strike (Str+d8, AP 2, +4 damage from Cavalry Charge), then switches to close combat. Uses Tusker\'s Gore and Hooves abilities to control the battlefield. Never dismounts voluntarily.\n\nCompanion — Tusker (War Boar): Agility d6, Smarts d4(A), Spirit d6, Strength d12, Vigor d10, Fighting d8. Pace 8, Parry 6, Toughness 9. Gore (Str+d6), Size 2, Hardy. Free Strength attack vs adjacent foe when moving 6\"+.'},
      {name:'Tallyman Oskar Venn',refCode:'AM-C030',concept:'The Professional',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria Weekly Pack W01',attrs:{agility:6,smarts:8,spirit:8,strength:6,vigor:6},skills:{'Common Knowledge':8,Fighting:6,Intimidation:8,Notice:8,Persuasion:8,Stealth:6},edges:[],hindrances:[],powers:[],gearText:'Neat clothes, ledger, club (Str+d4)',notes:'Week 01: The Counting Quarter.\n\nThe Brotherhood\'s most effective debt collector. Nothing personal. Thirty-four, neat clothes, ledger under arm. He explains terms clearly, offers payment plans, and apologises when violence becomes necessary. This makes him more frightening than the ones who enjoy it.\n\nWhat He Wants: To do his job well. To tithe to the Sacred Flame anonymously. To pretend that balances the books.\nHis Secret: He tithes 10% of his earnings to Aurelia\'s temples. It doesn\'t help him sleep.'},
      {name:'"Three-Fingers" Kael',refCode:'AM-C031',concept:'Scout — The Traitor',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria Weekly Pack W04',attrs:{agility:8,smarts:6,spirit:4,strength:6,vigor:6},skills:{Athletics:8,Fighting:4,Notice:8,Shooting:6,Stealth:10,Survival:10,Thievery:4},edges:['Alertness','Woodsman'],hindrances:['Obligation (Major — Brotherhood holds his sister Mira)','Loyal (Minor — to his sister above all else)','Yellow (Major)'],powers:[],gearText:'Bow (2d6, 12/24/48), hunting knife (Str+d4), forest clothes, concealed Brotherhood coin',quote:'I know every trail in the Guildwood. I know which ones will kill you. Right now, I can\'t remember which is which.',notes:'Week 04: The Amber Road — The Inside Man.\n\nTwenty-six. Lost two fingers to frostbite saving a merchant\'s daughter. Then his father\'s debts came due. The Brotherhood holds his sister Mira — she\'s seventeen.\n\nHe\'s sabotaged the lead wagon\'s axle and sent word of the route to Scarface Tomas. He hates himself. He\'s doing it anyway.\n\nHis Secret: The Brotherhood plans to sell his sister anyway once this job is done.\n\nBreaking Point: If confronted, Spirit roll. Failure = confesses. Success = flees. Won\'t fight anyone who isn\'t Brotherhood.\n\nConnections: Sister Mira held by Brotherhood (Week 12). Feeds info to Scarface Tomas.'},
      {name:'Tusker',refCode:'AM-C032',concept:'Valdos\'s War Boar',ancestry:'War Boar',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:4,spirit:6,strength:12,vigor:10},skills:{Athletics:6,Fighting:8,Notice:6},edges:[],hindrances:[],powers:[],gearText:'Gore (Str+d6), Size 2, Hardy',quote:'',notes:'Canal Bridge Ambush — Sergeant Valdos\'s mount.\n\nSpecial Abilities: Gore (Str+d6), Tusks & Hooves (free Strength attack vs adjacent foe when moving 6\"+), Size 2, Hardy.\n\nEnormous, scarred, and magnificently ill-tempered. Obeys Valdos without question and tolerates no one else.\n\nTactics: Charges into the thickest group, using Size 2 to bowl through opposition. Gore on the charge; Tusks & Hooves punish anyone standing adjacent.'},
      {name:'Vella Ashford',refCode:'AM-C033',concept:'Herbalist',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:10,spirit:8,strength:4,vigor:6},skills:{Healing:10,Notice:8,Occult:6,Research:8,Survival:8},edges:['Healer','Scholar'],hindrances:[],powers:[],gearText:'Herbalist\'s kit, rare plants, grandmother\'s journal (partially coded), 40-80₡',quote:'My grandmother was tribute-taken. I remember what she taught me.',notes:'Appendix D: Allies & Contacts.\n\nHer grandmother, tribute-taken fifty years ago, somehow escaped Glasrya — bringing knowledge of plants and medicines unknown to Ammarian practitioners. Vella continues that tradition, offering remedies that work suspiciously well.\n\nCautious, knowledgeable, secretly bitter about what the tribute system took from her family. Rebel sympathiser but not active.\n\nServices: Healing (Healing roll +2, 10₡), antidotes (+2 vs. specific poison, 25₡), knockout drugs (25₡+, discretion required)\n\nHook: Someone\'s been asking about Vella\'s grandmother — what she knew, what she brought back. Glasryan interest, perhaps, or usurper recruitment.'},
      {name:'Viktor Aldenberg',refCode:'AM-C034',concept:'The Corrupt Factor',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Seasoned',category:'NPC',product:'Ammaria Weekly Pack W01',attrs:{agility:6,smarts:10,spirit:8,strength:6,vigor:6},skills:{'Common Knowledge':10,Intimidation:8,Notice:8,Persuasion:10,Research:8,Stealth:6,Taunt:8},edges:['Streetwise','Connections','Strong Willed'],edgeNotes:{'Connections':'Brotherhood, senior guilds, Glasryan intermediaries'},hindrances:['Greedy (Major)','Ruthless (Minor)','Obligation (Major — his daughter was tribute-taken fifteen years ago)'],powers:[],gearText:'Expensive clothes, concealed dagger (Str+d4), 500₡ in various forms',quote:'Everyone has a price. The trick is finding out what currency they accept.',notes:'Week 01: The Counting Quarter / NPC Pack: Guild Factors.\n\nForty-one, soft hands, smile that arrives three seconds before it reaches his eyes. He doesn\'t blackmail — that\'s crude. He "facilitates." He "consults." He makes sure the right people know the right things at the right times.\n\nThe Brotherhood uses him. The guilds use him. The Glasryans probably use him.\n\nWhat He Wants: More. Always more. But underneath it all — to free his daughter from the Glasryan tribute system.\nHis Secret: He has a daughter tribute-taken fifteen years ago. Everything he does is ultimately aimed at freeing her.\n\nSpecial — The Fixer: Viktor can arrange meetings, acquire information, or solve problems. His price is always fair — and always collected.\n\nConnections: Hidden antagonist in The Counterfeit Seal. Manages Varen\'s "special accounting." Professional respect with Grandmother Holst.'},

      // === GENERIC NPC ARCHETYPES (EXTRAS) ===
      {name:'Caravan Guard',refCode:'AM-C035',concept:'Professional Escort',ancestry:'Human',region:'Ammaria',tier:'Extra',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:6,spirit:6,strength:8,vigor:8},skills:{Athletics:6,Fighting:8,Notice:8,Riding:6,Shooting:6,Survival:6},edges:['Alertness'],hindrances:['Loyal (Minor — to their employer)'],powers:[],gearText:'Ammarian breastplate (+4), halberd (Str+d8, Reach 1), repeating crossbow (2d6, AP 3, 15/30/60), shortsword (Str+d6), 5-15₡',quote:'Bandits ahead. Crossbows ready, bolts loaded. Wait for my signal.',notes:'Chapter 7: Bestiary & Non-Player Characters.\n\nProfessional escorts protecting trade caravans. Long hours of boredom punctuated by moments of terror — but it pays.\n\nTactics: Fight defensively using wagon cover and crossbow fire. Protect cargo before pursuing enemies. Rarely chase fleeing bandits.'},
      {name:'Gang Tallyman',refCode:'AM-C036',concept:'Criminal Debt Collector',ancestry:'Human',region:'Ammaria',tier:'Extra',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:8,spirit:8,strength:6,vigor:6},skills:{'Common Knowledge':8,Intimidation:8,Notice:8,Persuasion:8,Research:8,Stealth:4,Thievery:6},edges:['Connections','Investigator','Strong Willed'],edgeNotes:{'Connections':'Criminal network, street informants'},hindrances:['Greedy (Minor)','Loyal (Minor — to the gang boss)'],powers:[],gearText:'Quality clothing worth 75₡, concealed knife (Str+d4), ledger with coded accounts, 50-200₡',quote:'You borrowed money. You knew the terms. Now you owe. I\'m here to discuss repayment options.',notes:'Chapter 7: Bestiary & Non-Player Characters.\n\nTallymen handle financial operations for Ammaria\'s criminal gangs: tracking debts, assessing ability to pay, recommending pressure. Smarter than enforcers, more comfortable with numbers than violence.\n\nTactics: Don\'t fight. Talk, negotiate, threaten, and retreat to report.'},
      {name:'Guild Factor',refCode:'AM-C037',concept:'Mid-Ranking Guild Representative',ancestry:'Human',region:'Ammaria',tier:'Extra',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:8,spirit:6,strength:4,vigor:6},skills:{'Common Knowledge':8,Notice:6,Persuasion:8,Research:8,Stealth:4},edges:['Connections','Streetwise'],edgeNotes:{'Connections':'Parent guild, trading partners'},edgeNotes:{'Connections':'Timber Trade Association, blackmail leverage on senior guild members'},hindrances:['Obligation (Minor — guild duties and reporting requirements)'],powers:[],gearText:'Guild credentials, fine clothing, ledger, letters of credit, concealed knife (Str+d4), 50-100₡',quote:'The contract is quite clear. Shall I read the penalty clause aloud?',notes:'Chapter 7: Bestiary & Non-Player Characters.\n\nMid-ranking guild representatives handling negotiations, contracts, and trade disputes. Their goodwill opens doors; their displeasure closes them.\n\nTactics: Don\'t fight. Invoke guild authority, threaten commercial consequences, retreat behind bodyguards.'}
    ,

      // === CHAPTER 7: ADDITIONAL GENERIC ARCHETYPES ===
      {name:'Caravan Guard Captain',refCode:'AM-C038',concept:'Veteran Escort Commander',ancestry:'Human',region:'Ammaria',tier:'Extra',rank:'Seasoned',category:'NPC',product:'Ammaria',attrs:{agility:8,smarts:8,spirit:8,strength:8,vigor:8},skills:{Athletics:8,Battle:6,'Common Knowledge':8,Fighting:8,Intimidation:6,Notice:8,Persuasion:6,Riding:8,Shooting:8,Survival:8},edges:['Alertness','Command','Combat Reflexes','Caravan Guard'],hindrances:['Stubborn (Minor)'],powers:[],gearText:'Ammarian Breastplate (+4), repeating crossbow (2d6, AP 3, 15/30/60), Ammarian steel longsword (Str+d8, AP 1), light warhorse, 50-150₡',quote:'We\'ve got forty wagons, twelve guards, and three days of bandit country ahead. Everyone stays alert. Everyone follows orders.',notes:'Chapter 7: Bestiary & Non-Player Characters.\n\nCaptains use their Caravan Guard training to spot ambushes before they\'re sprung, gaining crucial first-round advantages. They command from positions offering clear views, committing to melee only when command isn\'t more valuable.\n\nTactics: Opens with crossbow fire from elevated position. Uses Command to boost guard morale. Only commits to melee when leadership isn\'t more effective.'},
      {name:'City Watch',refCode:'AM-C039',concept:'Guild-Employed Peacekeeper',ancestry:'Human',region:'Ammaria',tier:'Extra',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:6,spirit:6,strength:6,vigor:6},skills:{Athletics:6,'Common Knowledge':6,Fighting:6,Intimidation:6,Notice:6,Shooting:6},edges:[],hindrances:['Loyal (Minor — to the employing guild)'],powers:[],gearText:'Guild leathers (+2), shortsword (Str+d6), halberd (Str+d8, AP 1, Reach 1), repeating crossbow (2d6, AP 3, 15/30/60) with 12 bolts, manacles, signal whistle, lantern, 5-15₡',quote:'Move along. Guild business? Let\'s see your papers. That seal doesn\'t look right.',notes:'Chapter 7: Bestiary & Non-Player Characters.\n\nUniformed peacekeepers serving guild interests first and public safety second. Salaries modest; opportunities for supplemental income not. Most are ordinary people doing difficult work — arresting criminals when they can, taking bribes because refusing means poverty.\n\nTactics: Patrol in pairs, call reinforcements when outmatched. Use crossbows at range, capture rather than kill. Braver when protecting partners.'},
      {name:'Council Clerk',refCode:'AM-C040',concept:'Minor Bureaucrat',ancestry:'Human',region:'Ammaria',tier:'Extra',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:8,spirit:6,strength:4,vigor:6},skills:{'Common Knowledge':8,Notice:6,Persuasion:6,Research:8,Stealth:6},edges:['Scholar'],hindrances:['Greedy (Minor)','Cautious (Minor)'],powers:[],gearText:'Clerk\'s robes, writing supplies, keys to various offices, personal copies of interesting documents, 20-100₡ in accumulated fees',quote:'These forms take weeks to process. Unless... well, there are certain expediting fees that aren\'t strictly official. You understand.',notes:'Chapter 7: Bestiary & Non-Player Characters.\n\nMinor bureaucrats supplementing meagre salaries through creative interpretation of regulations. Their official authority is limited. Their practical power is considerable.\n\nBribe Scale: Minor favour 5-10₡; significant assistance 25-50₡; serious risk 100₡+.\n\nTactics: Don\'t fight. Cooperate when threatened, plan revenge through official channels. A clerk with a grudge ensures applications are denied, permits delayed, inspections scheduled at inconvenient times.'},
      {name:'Gang Boss',refCode:'AM-C041',concept:'Criminal Enterprise Leader',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Veteran',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:10,spirit:10,strength:6,vigor:6},skills:{'Common Knowledge':10,Fighting:8,Intimidation:10,Notice:10,Persuasion:10,Stealth:4,Taunt:8},edges:['Alertness','Command','Connections','Menacing','Strong Willed'],edgeNotes:{'Connections':'Criminal enterprises, corrupt Watch officers, Brotherhood'},hindrances:['Ruthless (Major)','Suspicious (Major)'],powers:[],gearText:'Quality clothing, concealed weapon (Str+d4), 2-4 enforcers within calling distance',quote:'You work for me, or you work against me. One of those pays better. The other pays faster.',notes:'Chapter 7: Bestiary & Non-Player Characters.\n\nGang bosses command criminal enterprises through cunning, reputation, and selective violence. Rarely fight personally — that\'s what enforcers are for — but none reached their position without proving they could handle themselves.\n\nTactics: Negotiate, threaten, manoeuvre. Fighting is failure. If cornered, remind attackers that killing them triggers consequences. Usually not bluffing.'},
      {name:'Gang Enforcer',refCode:'AM-C042',concept:'Criminal Muscle',ancestry:'Human',region:'Ammaria',tier:'Extra',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:8,smarts:6,spirit:6,strength:8,vigor:8},skills:{Athletics:6,Fighting:8,Intimidation:8,Notice:6,Stealth:6},edges:['Brawny','Combat Reflexes'],hindrances:['Loyal (Minor — to the gang boss)','Mean (Minor)'],powers:[],gearText:'Guild leathers (+2), shortsword (Str+d6), sap (Str+d4, non-lethal), brass knuckles (Str+d4), 20-50₡',quote:'The boss remembers. The boss collects. And I don\'t explain myself to people who still owe money.',notes:'Chapter 7: Bestiary & Non-Player Characters.\n\nProfessional muscle. Collect protection money, deliver warnings, eliminate problems requiring permanent solutions. The gangs value restraint — bodies attract Watch attention, and Watch attention costs money.\n\nTactics: Prefer intimidation to violence. Work in pairs or groups. Target legs and arms first, disabling rather than killing unless orders specify otherwise. Retreat when outmatched — pride is for amateurs.'},
      {name:'Night\'s Whisper Thief',refCode:'AM-C043',concept:'Professional Burglar',ancestry:'Human',region:'Ammaria',tier:'Extra',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:10,smarts:8,spirit:6,strength:6,vigor:6},skills:{Athletics:8,'Common Knowledge':6,Fighting:6,Notice:8,Persuasion:4,Stealth:10,Thievery:12},edges:['Acrobat','Thief'],hindrances:['Loyal (Minor — Night\'s Whisper guild)','Wanted (Minor — Ammarian Watch)'],powers:[],gearText:'Dark clothing, Ammarian lockpicks (+1 Thievery), guild knife (Str+d4, +1 conceal), grappling hook with silk rope, smoke bombs, 50₡+',quote:'The guild doesn\'t steal. We relocate assets to more appreciative owners.',notes:'Chapter 7: Bestiary & Non-Player Characters.\n\nNight\'s Whisper imposes strict professional standards: no unnecessary violence, no jobs attracting excessive attention, no betrayal under any circumstances.\n\nTactics: Don\'t fight — disappear. Smoke bombs cover retreats, acrobatics carry them to rooftops. Pre-planned escape routes lead to bolt holes. If cornered, surrender and trust the guild to arrange release. Dead thieves can\'t steal.'},
      {name:'Tide Reaver',refCode:'AM-C044',concept:'Elite Marine',ancestry:'Human',region:'Ammaria',tier:'Extra',rank:'Seasoned',category:'NPC',product:'Ammaria',attrs:{agility:8,smarts:6,spirit:8,strength:8,vigor:8},skills:{Athletics:10,Boating:8,Fighting:10,Intimidation:8,Notice:8,Shooting:8,Stealth:6},edges:['Sailor\'s Edge','Combat Reflexes','First Strike','Steady Hands','Block'],hindrances:['Loyal (Minor — Moonstar Consortium)','Ruthless (Minor)'],powers:[],gearText:'Reinforced leathers (+2), Ammarian steel cutlass (Str+d6+1, AP 1), hand crossbow (2d4, 5/10/20), boarding shield (+1 Parry, spiked Str+d4), smoke bombs, grappling hook',quote:'Hooks away. Kill the officers. Take the cargo. Leave no witnesses who can identify the ship.',notes:'Chapter 7: Bestiary & Non-Player Characters.\n\nElite boarding specialists. When ships need taking quickly and completely, Reavers handle the work. Selected from veteran marines demonstrating exceptional skill and absolute reliability.\n\nTactics: Hit hard and fast. Smoke bombs create confusion, grappling hooks close distance. Coordinated strikes eliminate officers before crew can organise. Target leaders first — leaderless crews surrender or scatter.'},

      // === APPENDIX D: ADDITIONAL ALLIES & CONTACTS ===
      {name:'Mira Copperhand',refCode:'AM-C045',concept:'Information Broker',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:6,smarts:10,spirit:6,strength:4,vigor:6},skills:{'Common Knowledge':12,Notice:8,Persuasion:6,Research:10,Stealth:6},edges:['Smuggler\'s Eye','Alertness','Photographic Memory'],hindrances:[],powers:[],gearText:'Clerk\'s clothing, personal ledger (coded), 30-50₡',quote:'I know where everything is. Finding it costs extra.',notes:'Appendix D: Allies & Contacts.\n\nFormer warehouse clerk who memorised the location of every significant cargo passing through Mottgorte\'s River Docks over fifteen years. Dismissed for skimming, now sells her encyclopaedic knowledge to anyone willing to pay.\n\nNervous, greedy, surprisingly principled about keeping her word once paid. Won\'t sell the same information twice.\n\nServices: Cargo location (5-20₡), warehouse security details (25-50₡), customs inspector bribes (current rates plus 10%)\n\nHook: Mira knows something dangerous — the location of a tribute shipment, perhaps, or which warehouse hides smuggled weapons. Someone wants her silenced.'},
      {name:'"Old Thom" Brackwater',refCode:'AM-C046',concept:'Retired River Pilot',ancestry:'Human',region:'Ammaria',tier:'Wild Card',rank:'Novice',category:'NPC',product:'Ammaria',attrs:{agility:8,smarts:6,spirit:8,strength:6,vigor:6},skills:{Boating:10,'Common Knowledge':8,Notice:8,Repair:6,Survival:8,Athletics:8},edges:['Sailor\'s Edge','Ace','Luck'],hindrances:['Elderly (Major)','One Eye (Major)'],powers:[],gearText:'Weather-worn coat, personal charts (invaluable), flask of cheap whiskey, river punt',quote:'Forty years on the Thrane. She\'s got no secrets from me.',notes:'Appendix D: Allies & Contacts.\n\nRetired river pilot who knows every sandbar, current, and hidden channel on the Thrane and its major tributaries. Lost his license after a cargo accident that wasn\'t entirely his fault.\n\nGruff, cynical, surprisingly sentimental about the river. Tells endless stories, most of which are true.\n\nServices: River piloting (guild rate minus 30%), smuggler channel navigation (double rates), tributary maps (50₡ per section), emergency extraction by river (negotiable)\n\nHook: Thom\'s found something on the river — wreckage from a vessel that shouldn\'t exist, or a tributary that\'s changed course to reveal ruins.'}
]
  });
})();

